Ajout reception
TSAP-Laval/acquisition-frontend pull request #172
Opened 2017-05-06 20:02 UTC by alexDeschenes

## Please follow the guide below

- Pull requests (PR) submitted without this template format will likely be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your PR (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting a pull request, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your pull request?
- [X] Bug fix (encountered problems/errors)
- [X] Feature (request of a new functionality)
- [ ] Enhancement
- [ ] Other

Ajout de la reception de l'action , fix des problèmes d'affichage au moment de la capture d'action et sourtout maintenant on fait 2 click et la flèche ce crée automatiquement comme le client voulait .Fichier modifier EditStore Edit  et EditAction . 

 https://github.com/TSAP-Laval/acquisition-frontend/issues/167

2017-05-06 21:58 UTC, laurentlp requested changes

2017-05-06 21:58 UTC, laurentlp commented on src/layouts/Edit.tsx
> +let idReception: any;
Met jamais any, à moins que la variable puisse être plus qu'un type durant l'exécution... Ce qui me surprendrais pour un identifiant ! Logiquement, cela devrait être une variable de type `number`. Pareille pour toutes les autres. Corrige cela s'il te plaît...

2017-05-06 21:58 UTC, laurentlp commented on src/layouts/Edit.tsx
>        text = "{"
JSON !!!

2017-05-09 13:08 UTC, laurentlp requested changes
Good, ça s'en vient bien ! Par contre, je veux que tu fasse un minimum de tests pour cette PR là !

2017-05-09 13:08 UTC, laurentlp commented on package.json
> +    "webpack": "^1.15.0",
Webpack c'est un plugin GLOBAL, ça ne donne rien de l'installer dans le dossier du projet

2017-05-16 16:49 UTC, laurentlp submitted a review, later dismissed
Oublie pas de review ma PR back-end, d'adapter tes trucs et de faire la même chose front-end !!!! Falloir que tu gère tout de suite l'authentification !

2017-05-16 16:49 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +    console.log("wowo");
???

2017-05-16 16:49 UTC, laurentlp commented on src/components/Manage/Seasons.tsx
> +    console.log(text)
???

2017-05-17 03:31 UTC, Alexandrehebertvincent approved these changes

2017-05-18 19:56 UTC, merged