fix front-end partie derniere(flux pas encore selon issue)
TSAP-Laval/acquisition-frontend pull request #71
Opened 2017-02-25 20:07 UTC by alexDeschenes

2017-02-25 20:40 UTC, laurentlp requested changes

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +
Enlève les espaces superflues plz!

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +             var doc = document.getElementById("tbody");
Pas oubligé de le faire là, mais le but de react c'est qu'il y a un DOM virtuel et donc tu n'a pas a  le reload au complet à chaque modifs. En faisant des creates, ca enlève la logique du framework...

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +	}
Mets des espaces entre tes fonctions!!! Assure toi que ton code est épuré et lisible, donc quand tu vas en prod enlève les tous code inutile (console, variables temporaires, etc)

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +                        <div className="row">
Assure toi aussi que tes indentations soient bonnes! 4 espaces partout va être la norme...

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/manageActions.tsx
> + export function PostSaison(stringContenu: string) {
Pourquoi une majuscule soudainement ?

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/manageActions.tsx
> + export function PostSaison(stringContenu: string) {
Toutes tes autres fonctions commencent par une minuscule !

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/manageActions.tsx
> +export function PostTeam(stringContenu: string) {
Encore

2017-02-25 20:40 UTC, laurentlp commented on src/components/Manage/manageActions.tsx
> +     export function PostJoueur(stringContenu: string) {
...

2017-02-25 20:40 UTC, laurentlp commented on src/index.tsx
> +
Pas besoin de toutes ces espaces :)

2017-02-25 20:40 UTC, laurentlp commented on src/layouts/Layout/Navbar.tsx
> +            /*<SideNav
Tant qu'à ce que ca soit tout commenté, on pourrait l'enlever

2017-02-25 20:40 UTC, laurentlp commented on src/pages/edit.tsx
> +  //import Footer from "../layouts/Footer"
Inutile

2017-02-25 20:40 UTC, laurentlp commented on src/pages/edit.tsx
> +
Why no footer ?

2017-02-25 20:40 UTC, laurentlp commented on src/sass/_alexd.scss
>  #Enr.form-open {
Pas de maj plz pour le nom de tes class ou id css, pi aussi _ pour les espaces plz

2017-02-25 20:40 UTC, laurentlp commented on src/sass/_variables.scss
> +$primary:  #000;
Deux fois $primary ?

2017-02-25 20:42 UTC, laurentlp commented
Aussi pas de yarn*
Genre il faudrait mettre une exception dans le .gitignore sur : 

- yarn-error.log
- yarn.lock

2017-02-25 20:43 UTC, laurentlp commented
Prochaine fois ta branche devrait être par exemple partie_derniere. Mets pas de maj, jamais!
Mais laisse ca comme ca pour celle là...

2017-02-25 20:48 UTC, alexDeschenes commented on src/sass/_variables.scss
> +$primary:  #000;
corrigé

2017-02-25 20:50 UTC, laurentlp commented on src/sass/_variables.scss
> +$primary:  #000;
OK ben push

2017-02-25 20:53 UTC, alexDeschenes commented on src/pages/edit.tsx
> +
corrigé

2017-02-25 20:54 UTC, alexDeschenes commented on src/pages/edit.tsx
> +  //import Footer from "../layouts/Footer"
corrigé

2017-02-25 20:54 UTC, laurentlp commented on src/pages/edit.tsx
> +  //import Footer from "../layouts/Footer"
plz

2017-02-25 20:54 UTC, laurentlp commented on src/pages/edit.tsx
> +  //import Footer from "../layouts/Footer"
Fais juste push ma voir ton code comme ca !!!!

2017-02-25 20:55 UTC, alexDeschenes commented on src/layouts/Layout/Navbar.tsx
> +            /*<SideNav
je n'ai pas touché à cette partie donc

2017-02-25 20:56 UTC, laurentlp commented on src/layouts/Layout/Navbar.tsx
> +            /*<SideNav
Good, mais tu peux quand meme l'enlever!
T'as juste a t'assurer que la nav bar est encore la apres...

2017-02-25 20:56 UTC, alexDeschenes commented on src/index.tsx
> +
corrigé :)

2017-02-25 20:57 UTC, alexDeschenes commented on src/components/Manage/manageActions.tsx
> +     export function PostJoueur(stringContenu: string) {
corrigé

2017-02-25 20:57 UTC, laurentlp commented on src/index.tsx
> +
PLZ ARRETE DE ME LE DIRE C'EST GOOD..... PUSH C'EST TOUT!!!!!!!!!!!!!!!!!!!!!!!!

2017-02-25 20:58 UTC, alexDeschenes commented on src/components/Manage/manageActions.tsx
> +export function PostTeam(stringContenu: string) {
corrigé

2017-02-25 21:14 UTC, alexDeschenes commented on src/components/Manage/Players.tsx
> +             var doc = document.getElementById("tbody");
good je sais que c'était pas parfait je vais regarder avec les autres parties voir comment on fait  sinon le reste c'est corrigé

2017-02-25 21:15 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +             var doc = document.getElementById("tbody");
Good, as tu push !!!!

2017-02-25 21:43 UTC, laurentlp requested changes

2017-02-25 21:43 UTC, laurentlp commented on src/components/Manage/Seasons.tsx
> +					<table className="table table-bordered table-hover" >
WTF

2017-02-25 21:47 UTC, laurentlp requested changes

2017-02-25 21:47 UTC, laurentlp commented on src/Manage/Actions.tsx
> +                    <div className="container-fluid">
ICI aussi mauvaise indentation

2017-02-25 21:47 UTC, laurentlp commented on src/Manage/Seasons.tsx
> +				<thead>
Mauvaise indentation

2017-02-25 21:47 UTC, laurentlp commented on src/Manage/Teams.tsx
> +						</th>
Mauvaise indentation

2017-02-25 21:47 UTC, laurentlp commented on src/Manage/manage_style.scss
> +			font-family: Arial, Helvetica, sans-serif;
Mauvaise indentation

2017-02-25 21:47 UTC, laurentlp commented on src/components/Manage/Manage.tsx
> +    <Tabs>
Mauvaise indentation

2017-02-25 21:47 UTC, laurentlp commented on src/components/Manage/Players.tsx
> +			  var tdNom = document.createElement("td");
Mauvaise indentation

2017-02-25 21:49 UTC, alexDeschenes commented on src/Manage/Actions.tsx
> +                    <div className="container-fluid">
partie a medhi mais je peux la faire au pire

2017-02-25 21:49 UTC, laurentlp commented on src/components/Manage/Seasons.tsx
> +					<table className="table table-bordered table-hover" >
Mauvaise indentation

2017-02-25 22:23 UTC, laurentlp requested changes

2017-02-25 22:23 UTC, laurentlp commented on src/components/Manage/Seasons.tsx
Plein d'indentations incorrecte encore!

2017-02-25 22:26 UTC, alexDeschenes commented on src/components/Manage/Seasons.tsx
ou?

2017-02-28 21:35 UTC, laurentlp approved these changes
Alright!!!

2017-02-28 21:35 UTC, laurentlp commented
Squash and Merge plz! Fais pas juste un Merge pull request

2017-03-01 01:30 UTC, merged