Modif joueur
TSAP-Laval/acquisition-frontend pull request #90
Opened 2017-03-17 19:07 UTC by alexDeschenes

## Please follow the guide below

- Pull requests (PR) submitted without this template format will likely be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your PR (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting a pull request, make sure you have:
- [ ] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [ ] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your pull request?
- [ ] Bug fix (encountered problems/errors)
- [ ] Feature (request of a new functionality)
- [ ] Enhancement
- [ ] Other

### If people needs to do some things, include them with their tasks as shown bellow:
1. The title and description of the task.
    - [X] Alex D
    - [ ] Alex H
    - [ ] Mehdi
    - [ ] Laurent

---

2017-03-17 19:10 UTC, laurentlp requested changes

2017-03-17 19:10 UTC, laurentlp commented on src/components/Manage/Coachs.tsx
> +<<<<<<< HEAD
Full conflits

2017-03-17 19:10 UTC, laurentlp commented on src/components/Manage/Actions.tsx
> +>>>>>>> dev
Conflit

2017-03-17 19:15 UTC, alexDeschenes commented on src/components/Manage/Coachs.tsx
> +<<<<<<< HEAD
wtf j'ai pas sa moi dans mon code et toute est push

2017-03-17 19:23 UTC, laurentlp requested changes

2017-03-17 19:23 UTC, laurentlp commented on src/components/Manage/Actions.tsx
> +import * as $ from "jquery"
PK JQuery ?

2017-03-17 19:25 UTC, alexDeschenes commented on src/components/Manage/Actions.tsx
> +import * as $ from "jquery"
@mLaribi

2017-03-17 21:02 UTC, laurentlp commented
Genre arrange dont la description de ta PR aussi, c'est pas pour rien que j'ai mis un template....

2017-03-18 02:47 UTC, laurentlp commented on src/components/Manage/Coachs.tsx
> +<<<<<<< HEAD
Il faut que tu pull !

2017-03-19 19:38 UTC, laurentlp commented
Tu as des conflits a cause de mes ajouts faic pull le code et fix les plz @alexDeschenes

2017-03-19 19:38 UTC, laurentlp commented on src/components/Manage/Actions.tsx
> +import * as $ from "jquery"
Yo @mLaribi

2017-03-20 00:56 UTC, laurentlp commented
Arrange la description avant @alexDeschenes

2017-03-20 01:17 UTC, laurentlp commented
👍

2017-03-20 01:59 UTC, laurentlp approved these changes

2017-03-20 02:03 UTC, merged